travis:
  secure:
    BINSTAR_TOKEN: nzDOYR0spp+bsAfaclkfnlKTwQSeEphomQ8UIOxW+I15y+pqRBSSqsZWz691mV5+FDGvcGCAOyDrbgjmG7wCjqy2XsIfojTVtrCQCFGdVpMXO+4BjKZsWW6lMJXgaWF85NivLaQGVR4w2wxgNh1tw5md6WZgKuk3dsuD/NYzOSRAeU8DYr7kba6S6J7OaTMSKG7T38F6bv1GuwAOBeXepkLIj2/NL/Y+ludpgGiJN9NelfHjXInnhs9z+ZU5dIX+KYdMXxsVfjqk+ZJZcaNN1homuTfaej42AGBEw5ZNgWf0Rr4+JV585X3CO4gvdsyClgaD5for5kskI++dGm3Jdl93IK+234xGyI9I0Waa5YgBey7jxRXFiYFrI2nt6Sk3QKuna7p7m0yB1ohJLkp6G4Drb0DRCjirWocUYYNqirmHrM3lLyMdrK37toy1KrZrRaocZDD1rufIxhUMlfh8102cz2NoklE/T1HR2o1u2gzHJSvcspURAYHFvGhZB6fdHKRzUVfUFcbAMlC7iZ1YN3AlFV4QsJc1Y9Bd85IqgfQiJsvhayN4LWsAHjfj2MtwHHmlmvX1/CFOBNeGQrsD1pY3dYnEUF4Of2otuwlRNRWA4nGQRLyP4CnzvVOFeDnFL/hmNLvdTDhb7TnKIaM+mWc1hBSA6htbPWxBi/x8870=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
